---
- name: Install Python 3
  package:
    name: python34
- name: Install pip3 (python3-pip)
  package:
    name: python3-pip
  register: pip3_result
  ignore_errors: yes
- name: Install pip3 (python34-pip)
  package:
    name: python34-pip
  when: pip3_result|failed
- name: Install docker
  package:
    name: docker
- name: Start docker daemon
  service:
    name: docker
    state: started
- name: Install docker python library for ansible
  pip:
    name: docker-py
- name: Install SELinux python bindings (for systemd setup)
  package:
    name: libselinux-python
- name: Stop systemd service for "{{ instance_name }}"
  service:
    name: "{{ instance_name }}"
    state: stopped
  ignore_errors: yes
- name: Stop docker instance
  docker_container:
    name: "{{ instance_name }}"
    state: absent
- name: Create patchew data folder
  file:
    path: "{{ data_dir }}"
    state: directory
- name: Copy source
  synchronize:
    src: ../../../
    dest: "{{ src_dir }}"
    recursive: true
    group: no
    owner: no
    delete: yes
    rsync_opts:
      - "--exclude=*.pyc"
      - "--exclude=*.swp"
      - "--exclude=/venv"
- name: Delete old docker image stash
  docker_image:
    force: yes
    name: "patchew:{{ instance_name }}-prev"
    state: absent
- name: Stash docker image
  shell: docker tag "patchew:{{ instance_name }}" "patchew:{{ instance_name }}-prev" || true
- name: Rebuild docker image
  # docker_image module doesn't work on Fedora
  shell: docker build -t "patchew:{{ instance_name }}" -f "{{ src_dir }}/scripts/dockerfiles/{{ instance_role }}.docker" "{{ src_dir }}"
- name: Install systemd service
  template:
    src: "templates/docker.service.j2"
    dest: "/etc/systemd/system/{{ instance_name }}.service"
- name: Systemd daemon reload
  systemd:
    daemon_reload: yes
- name: Start docker instance
  service:
    name: "{{ instance_name }}"
    state: restarted
    enabled: yes
