# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-07 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.contrib.postgres.operations import TrigramExtension

from api.migrations import PostgresOnlyMigration


class Migration(PostgresOnlyMigration):

    dependencies = [
        ('api', '0049_populate_message_flags'),
    ]

    operations = [
        TrigramExtension(),
        migrations.RunSQL("create index api_message_flags_gin on api_message using gin(flags gin_trgm_ops);",
                          "drop index api_message_flags_gin"),
    ]
