# Generated by Django 3.1.14 on 2022-02-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0060_auto_20210106_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='searched_subject',
            field=models.CharField(default='', max_length=4096),
            preserve_default=False,
        ),
    ]
