- hosts: servers
  vars_prompt:
    - name: instance_name
      prompt: "Instance name of the webserver"
      default: patchew-server
      private: no
    - name: container_dir
      prompt: "The base directory for the container"
      default: /data
      private: no
    - name: db_host
      prompt: "Host for PostgreSQL database (empty = SQLite)"
      default: ""
      private: no
    - name: superuser_name
      prompt: "Admin account to create (optional)"
      default: ""
      private: no
    - name: superuser_pass
      prompt: "Admin password (optional)"
      default: "adminpass"
      private: yes
  vars:
    base_dir: "{{ container_dir }}/{{ instance_name }}"
    src_dir: "{{ base_dir }}/src"
    data_dir: "{{ base_dir }}/data"
    db_arg: "{{ '-e PATCHEW_DB_PORT_5432_TCP_ADDR=' if db_host != '' else '' }}{{ db_host }}"
    docker_run_args: "--link {{ instance_name }}-db:patchew-db {{db_arg}}"
  tasks:
    - name: Create data dir
      file:
        path: "{{ data_dir }}"
        state: directory
    - import_tasks: tasks/docker-deploy.yml
      vars:
        instance_role: server
    - name: Create superuser
      when: superuser_name != ""
      shell: |
        docker exec -i {{ instance_name }} bash -c "
        cd /opt/patchew &&
        . venv/bin/activate &&
        ./manage.py migrate &&
        (
        echo 'from django.contrib.auth.models import User;'
        echo 'if not User.objects.filter(username=\"{{ superuser_name }}\").first():'
        echo '    User.objects.create_superuser(\"{{ superuser_name }}\",'
        echo '                                  \"{{ superuser_name }}@example.com\",'
        echo '                                  \"{{ superuser_pass }}\")'
        ) | ./manage.py shell
        "
