- hosts: db
  vars_prompt:
    - name: instance_name
      prompt: "Instance name of the patchew postgres db"
      default: patchew-server-db
      private: no
    - name: container_dir
      prompt: "The base directory for the container"
      default: /data
      private: no
  vars:
    base_dir: "{{ container_dir }}/{{ instance_name }}"
    src_dir: "{{ base_dir }}/src"
    data_dir: "{{ base_dir }}/data"
  tasks:
    - name: Create data dir
      file:
        path: "{{ data_dir }}"
        state: directory
    - import_tasks: tasks/docker-deploy.yml
      vars:
        instance_role: db
