- hosts: testers
  vars_prompt:
    - name: instance_name
      prompt: "The instance name"
      default: patchew-tester
      private: no
    - name: "patchew_server"
      prompt: "The address of patchew server"
      default: "https://patchew.org"
      private: no
    - name: "tester_user"
      prompt: "Username for the tester to login to the server"
      private: no
      default: "tester"
    - name: "tester_pass"
      prompt: "Password for the tester to login to the server"
      private: yes
    - name: "tester_project"
      prompt: "Project name to test"
      private: no
  vars:
    base_dir: "/data/{{ instance_name }}"
    src_dir: "{{ base_dir }}/src"
    patchew_cmd: "{{ src_dir }}/patchew-cli -s {{ patchew_server }}"
  tasks:
    - debug:
        msg: Patchew tester deploy starting
    - name: "Ensure user patchew exists"
      user:
        name: patchew
        shell: /bin/bash
        state: present
    - name: Create patchew data folder
      file:
        path: "{{ base_dir }}"
        state: directory
    - name: Copy source
      synchronize:
        src: ../../../
        dest: "{{ src_dir }}"
        recursive: true
        group: no
        owner: no
        delete: yes
        rsync_opts:
          - "--exclude=*.pyc"
          - "--exclude=*.swp"
          - "--exclude=/venv"
    - name: Generate password file
      shell: "echo {{ tester_pass }} > $HOME/.patchew-tester-pass"
      become: true
      become_user: patchew
    - name: Login with patchew-cli
      shell: "{{ patchew_cmd }} login {{ tester_user }} $(cat $HOME/.patchew-tester-pass)"
      become: true
      become_user: patchew
    - name: Logout with patchew-cli
      shell: "{{ patchew_cmd }} logout"
      become: true
      become_user: patchew
    - name: Define PATCHEW env in cron
      cron:
        name: PATCHEW
        user: patchew
        env: yes
        value: "{{ patchew_cmd }}"
    - cron:
        name: "Patchew tester {{ instance_name }}"
        user: patchew
        minute: "*/10"
        job: "{ $PATCHEW login {{ tester_user }} $(cat $HOME/.patchew-tester-pass); $PATCHEW tester --name {{ instance_name }} --singleton -p {{ tester_project }}; } >>$HOME/patchew-tester.log 2>&1"
